import Head from 'next/head'
import React, { useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {

  const [ zipcode, setZipcode ] = React.useState("");
  const [ prefecture, setPrefecture ] = React.useState("");
  const [ city, setCity ] = React.useState("");
  const [ town, setTown ] = React.useState("");

//  // ReachHookでfetchメソッドでデータを取得
//  React.useEffect( ()=> {
//
//    // 郵便番号を数字７桁に変換
//    let iZipcode = zipcode.replace("-", "");
//
//    // APIからデータ取得
//    fetch( 'https://api.zipaddress.net/?zipcode=' + iZipcode )
//      .then( response => response.json() )
//      .then( result => {
//        // データがあれば設定し、無ければクリア
//        if(     result !== null
//            &&  result.code == '200'
//            )
//        {
////console.log( result );
//          setPrefecture( result.data.pref );
//          setCity( result.data.city );
//          setTown( result.data.town );
//        }
//        else
//        {
//          setPrefecture( "" );
//          setCity( "" );
//          setTown( "" );
//        }
//      });
//  });
// // ,[ zipcode, prefecture, city, town ]);

  // ReachHookでfetchメソッドでデータを取得
  React.useEffect( ()=> {

    // 郵便番号を数字７桁に変換
    let iZipcode = zipcode.replace("-", "");

    // APIからデータ取得
    fetch( 'https://zipcloud.ibsnet.co.jp/api/search?zipcode=' + iZipcode )
      .then( response => response.json() )
      .then( result => {
        // データがあれば設定し、無ければクリア
        if(     result !== null
            &&  result.status == '200'
            )
        {
//console.log( result );

          // とりあえず複数取れても１件目を設定
          setPrefecture( result.results[0].address1 );
          setCity( result.results[0].address2 );
          setTown( result.results[0].address3 );
        }
        else
        {
          setPrefecture( "" );
          setCity( "" );
          setTown( "" );
        }
      });
  });
 // ,[ zipcode, prefecture, city, town ]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js 郵便番号->住所変換テスト</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <h1>
          Next.js 郵便番号->住所変換テスト
        </h1>

        <div>
          <div>
            <span>郵便番号：</span>

            <input
              type="text"
              value={zipcode}
              onChange= { (e) => setZipcode( e.target.value )}
              />
          </div>
          
          <div>
            <span>都道府県：</span>

            <input
              type="text"
              value={prefecture}
              onChange= { (e) => setPrefecture( e.target.value )}
              />
          </div>
          
          <div>
            <span>市区町村：</span>

            <input
              type="text"
              value={city}
              onChange= { (e) => setCity( e.target.value )}
              />
          </div>
          
          <div>
            <span>町名　　：</span>

            <input
              type="text"
              value={town}
              onChange= { (e) => setTown( e.target.value )}
              />
          </div>
        </div>

        <div>
              ※複数件が取れる郵便番号「939-0351」「861-0000」
            </div>
      </main>

    </div>
  )
}
